import type { Metadata } from "next";
import "./globals.css";
import { nunito, nunitoSans } from "./fonts";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${clsx(nunito.variable, nunitoSans.variable)} antialiased`}>
      <body>
        {children}
      </body>
    </html>
  );
}
